travel/models.py
from . import db
import time
from datetime import datetime
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__='users' # good practice to specify table name
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), index=True, unique=True, nullable=False)
    emailid = db.Column(db.String(100), index=True, nullable=False)
	#password is never stored in the DB, an encrypted password is stored
	# the storage should be at least 255 chars long
    password_hash = db.Column(db.String(255), nullable=False)

    # relation to call user.comments and comment.created_by
    comments = db.relationship('Comment', backref='user')


class Destination(db.Model):
    __tablename__ = 'destinations'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(200))
    image = db.Column(db.String(400))
    currency = db.Column(db.String(3))
    updated_at = db.Column(db.Integer, default=int(time.time()))
    # ... Create the Comments db.relationship
	# relation to call destination.comments and comment.destination
    comments = db.relationship('Comment', backref='destination')
	
    def __repr__(self): #string print method
        return "<Name: {}>".format(self.name)

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(400))
    created_at = db.Column(db.DateTime, default=datetime.now())
    #add the foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    destination_id = db.Column(db.Integer, db.ForeignKey('destinations.id'))


    def __repr__(self):
        return "<Comment: {}>".format(self.text)

travel/forms.py
from datetime import date, datetime
from travel import create_app
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField,SubmitField, StringField, PasswordField
from wtforms.validators import InputRequired, Length, Email, EqualTo
from flask_wtf.file import FileRequired, FileField, FileAllowed


ALLOWED_FILE = {'png', 'jpg', 'JPG', 'PNG'}

#creates the login information
class LoginForm(FlaskForm):
    user_name=StringField("User Name", validators=[InputRequired('Enter user name')])
    password=PasswordField("Password", validators=[InputRequired('Enter user password')])
    submit = SubmitField("Login")

 # this is the registration form
class RegisterForm(FlaskForm):
    user_name=StringField("User Name", validators=[InputRequired()])
    email_id = StringField("Email Address", validators=[Email("Please enter a valid email")])
    
    #linking two fields - password should be equal to data entered in confirm
    password = PasswordField('Password', validators=[InputRequired(),
                         EqualTo('confirm',
                         message="Passwords must match")])
    confirm = PasswordField("Confirm Password")
    #submit button
    submit = SubmitField("Register")

class DestinationForm(FlaskForm):
    name = StringField('Country', validators=[InputRequired()])
    # adding two validators, one to ensure input is entered and other to check if the 
    #description meets the length requirements
    description = TextAreaField('Description', 
                validators=[InputRequired()])
    image = FileField('Destination Image', validators=[
        FileRequired(message="Image can not be empty"),
        FileAllowed(ALLOWED_FILE, message="Only supports png, jpg, JPG, or PNG file types")])
    currency = StringField('Currency', validators=[InputRequired()])
    submit = SubmitField("Create")

  
class CommentForm(FlaskForm):
    text = TextAreaField('Comment', [InputRequired()])
    created_at = datetime.now()
    submit = SubmitField('Post Comment')

travel/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()


def create_app():


    app = Flask(__name__)
    app.debug = True
    app.secret_key = 'somethingsecret'
    #c config the image upload
    UPLOAD_FOLDER = '/static/image'
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    # config the db
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///travel_data.sqlite'
    # initialise
    db.init_app(app)

    bootstrap = Bootstrap(app)

    from . import errors
    app.register_blueprint(errors.bp)

    from . import views
    app.register_blueprint(views.mainbp)

    from . import auth
    app.register_blueprint(auth.bp)

    from . import destinations
    app.register_blueprint(destinations.bp)

    # initialize the login manager
    login_manager = LoginManager()
    # set the name of the login function that lets user login
    # in our case it is auth.login (blueprintname.viewfunction name)
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # create a user loader function takes userid and returns User
    from .models import User  # importing here to avoid circular references

    @login_manager.user_loader  
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

travel/auth.py
from travel.errors import urlnotfound
from flask import (
    Blueprint, flash, render_template, request, url_for, redirect
)
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from .forms import LoginForm, RegisterForm
from flask_login import login_user, logout_user, login_required
from . import db


# create a blueprint
bp = Blueprint('auth', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit() == True):
        # get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        # if there is no user with that name
        if u1 is None:
            error = 'Incorrect user name'
        # check the password - notice password hash function
        # takes the hash and password
        elif not check_password_hash(u1.password_hash, password):
            error = 'Incorrect password'
        if error is None:
            # all good, set the login_user of flask_login to manage the user
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    # the validation of form submit is fine
    if (register.validate_on_submit() == True):
        # get username, password and email from the form
        uname = register.user_name.data
        pwd = register.password.data
        email = register.email_id.data
        # check if a user exists
        u1 = User.query.filter_by(name=uname).first()
        if u1:
            flash('User name already exists, please login')
            return redirect(url_for('auth.login'))
        # don't store the password - create password hash
        pwd_hash = generate_password_hash(pwd)
        # create a new user model object
        new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
        db.session.add(new_user)
        db.session.commit()
        # commit to the database and redirect to HTML page
        return redirect(url_for('main.index'))
    # the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')


@bp.route('/logout')  
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

travel/views.py
import time
from travel.models import Destination
from flask import Blueprint, render_template, url_for, request, session, templating, redirect

mainbp = Blueprint('main', __name__)


@mainbp.route('/')
def index():
    destinations = Destination.query.all()
    return render_template('index.html', destinations=destinations, epoch=time.time())

# route to allow users to search


@mainbp.route('/search')
def search():
    # get the search string from request
    if request.args['search']:
        dest = "%" + request.args['search'] + '%'
    # use filter and like function to search for matching destinations
        destinations = Destination.query.filter(Destination.name.like(dest)).all()
    # render index.html with few destinations
        return render_template('index.html', destinations=destinations, epoch=time.time())
    else:
        return redirect(url_for('main.index'))
        

travel/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>My Travel App - {%block title %} {% endblock %}</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
   <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

</head>

<style>
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 60px; /* Margin bottom by footer height */
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px; /* Set the fixed height of the footer here */
  background-color: #f5f5f5;
}

main{
   margin-bottom: 10px;
}
</style>

<body>
   <!-- Header -->
   <header class="bg-light border-bottom">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
         <div class="container">

            <!-- Your Travel App Name or Logo -->
            <a href="/" class="navbar-brand">
               My Travel App
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
               data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
               aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar -->
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
               <div class="navbar-nav ml-auto">
                  <a class="nav-item nav-link" href="/#destinations">Destinations</a>

                  {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="/destinations/create">Create A Destination</a>
                  {% endif %}
               </div>
            </div>
               <div class="navbarTogglerDemo01">
               {% if current_user.is_authenticated %}
               <a class="nav-item nav-link disabled text-muted" href="#"><span>Welcome, {{ current_user.name
                     }}</span></a>
               <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
               {% else %}
               <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
               <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
               {% endif %}
            </div>

         </div>
         </div>
      </nav>
      {% block header %}
      {% endblock %}
   </header>
   <main>

   <div class="container">
   {% block content %}

   {% endblock %}
   </div>
   </main>

   <footer class="footer">
      <div class="text-center py-2 bg-light">
         <span class="text-dark">Copyright &copy; Charlie Turner 2021</span>
      </div>
   </footer>

   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
      integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
      crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
      integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
      crossorigin="anonymous"></script>
</body>

</html>

travel/templates/destinations/create.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">

        <h1>Add Travel Destination</h1>
        <p>Enter a country that you will help clients travel to.</p>

        {{wtf.quick_form(form)}}
        
      </div>
    </div>
  </div>

{% endblock %}

travel/templates/destinations/delete.html
{% import "bootstrap/wtf.html" as wtf %} {% extends 'base.html' %}

travel/templates/destinations/show.html
{% import "bootstrap/wtf.html" as wtf %}


{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row mt-5 mb-3">
    <div class="col-md-12">
      <div class="float-left">
        <h1 class="mb-0"> {{ destination.name }}</h1>
        {% if current_user.is_authenticated %}
        <a href="deletedestination?destination={{destination.id}}">Delete Destination</a>
        {% endif %}
        <p>Popular Destination</p>
      </div>

      <div class="float-right text-right">
        <p class="mb-0">1 AUD equals</p>
        <h2 id="exchange-rate"> {{ destination.currency }} </h1>
      </div>
    </div>
  </div>

  <!-- Destination -->
  <div class="row">
    <div class="col-md-12">
      <div class="card my-3">
        <div class="card-body">
          <div class="media">
            <img class="align-self-start mr-3" src="{{destination.image}}" alt="destination image"
              style="max-width: 250px;">
            <div class="media-body">
              <small class="font-weight-bold text-muted">Stay 2 nights</small>
              <h5 class="mt-0">{{ destination.name }}</h5>
              <p> {{ destination.description }} </p>
              <a href="#" class="btn btn-danger">Book Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <hr>

  <!-- Form rendering is simple and easy if using bootstrap -->



  <hr>

  <!-- Comments -->
  <div class="row">
    <div class="col-md-12">
      <h2>Comments</h1>
    </div>
  </div>

   {{ wtf.quick_form(form, "/destinations/{0}/comment".format(destination.id)) }}

  

  <div class="row border-bottom">
    {% for comment in destination.comments %}
    <div class="col-md-12">
      <b>{{ comment.user.name }} <span class="ml-2 text-muted"> {{ comment.created_at.strftime("%d/%m/%Y %H:%M:%S") }} </span> <span>{% if comment.user == current_user %} <a href=>Delete Comment</a> {% endif %}</span></b>
      <p> {{ comment.text }} </p>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock %}

travel/templates/error.html
{% extends "base.html" %} {# Inherit from base.html #}
 
{% block content %}
<h2><center>Oops, something went wrong<center></h2>
<p>Error details: {{error}}</p>
{% endblock %}

travel/templates/index.html
{% extends 'base.html'%} {% block title %}Home{% endblock %} {% block header %}
<!--Jumbotron-->
<div class="container">
  <div class="row justify-content-center mt-5 pb-4">
    <div class="col-md-8">
      <div class="card shadow p-5 mb-5 bg-light">
        <h1 class="text-center mb-3">Find our best travel deals</h1>
        <form
          class="form-inline d-flex flex-nowrap"
          action="{{url_for('main.search')}}"
        >
          <input
            type="text"
            name="search"
            class="form-control flex-grow-1 my-1 mr-sm-2"
            placeholder="Search for a destination"
          />
          <button type="submit" class="flex-shrink-1 btn btn-primary my-1">
            Submit
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block content %} {% if current_user.is_authenticated == false
%}
<div class="row mt-5 mb-5 justify-content-center">
  <div class="col-md-10">
    <div class="media border p-3 d-flex justify-content-start">
      <img
        class="align-self-center me-3"
        style="max-width: 120px"
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png"
        alt="Planet Earth"
      />

      <div class="align-self-center media-body">
        <h5 class="mt-0">Find the best destinations on earth</h5>
        <p class="d-none d-sm-block">
          Sign up to enjoy access to reviewing and booking destinations
        </p>
        <a href="/register" class="btn btn-primary">Join Now</a>
      </div>
    </div>
  </div>
</div>
{% endif %}
<div class="row destinations card-deck">
  {% for destination in destinations %} {# loop through the passed destination
  list and create a card for each #}
  <div class="col-md-4 col-lg-3">
    <div class="card">
      <img class="card-img-top" src="{{destination.image}}" />
      <div class="card-body">
        <h5 class="card-title">{{ destination.name }}</h5>
        <a
          href="{{url_for('destination.show', id=destination.id)}}"
          class="btn btn-danger"
          >View Details</a
        >
      </div>
      <div class="card-footer">
        <small class="text-muted">
          Last updated {{ ((epoch -
          destination.updated_at)/(60*60*24))|round|int }} days ago</small
        >
      </div>
    </div>
  </div>
  {%endfor%}
</div>
{% endblock %}

travel/templates/user.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}

<div class="container-fluid">
  {% block content %}

  <div class="page-header">
    <h4>{{heading}}</h4>
  </div>

  {% with messages = get_flashed_messages() %} {% if messages %}
  <!-- check if there are any messages -->
  <div class="container-fluid">
    <div class="row mt-3 mb-3">
      <div class="col-md-12">
        {% for message in messages %}
        <!--loop through the messages-->
        <div class="alert alert-info">{{ message }}</div>
        <!--display as alert-->
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %} {% endwith %}

  <!-- Form rendering is simple and easy if using bootstrap -->
  <div class="col-md-6 mx-auto">{{wtf.quick_form(form)}}</div>

  <!-- When you have login form, then do show the user a link to register -->
  {% if heading|lower =='login' %}
  <div class="col-md-4 mb-5 ml-5">
    <p>
      New user?
      <a href="{{ url_for('auth.register') }}">Click here to register</a>.
    </p>
  </div>
  {% endif %} {% endblock %}
</div>